import type { Metadata } from "next";
import { buildPageMeta } from "@/lib/constants/seo";
import { CssGradientClient } from "./CssGradientClient";

export const metadata: Metadata = buildPageMeta({
  title: "CSS Gradient Generator & Tailwind Exporter",
  description:
    "Create stunning linear, radial, and conic CSS gradients. Live preview, customize color stops, and export instantly to standard CSS or Tailwind utility classes.",
  path: "/tools/css-gradient",
});

export default function CssGradientPage() {
  return (
    <>
      <CssGradientClient />

      {/* SEO & Context Content */}
      <div className="mt-16 mx-auto max-w-5xl pt-8 border-t border-border prose prose-sm dark:prose-invert">
        <h2 className="text-lg font-semibold text-foreground mb-4">Mastering CSS Gradients</h2>
        <p className="text-muted leading-relaxed mb-6">
          CSS gradients let you display smooth transitions between two or more specified colors. 
          Unlike traditional images, gradients are generated by the browser natively, meaning they scale perfectly, save bandwidth, and perform significantly better.
        </p>

        <h3 className="text-md font-semibold text-foreground mb-3">Types of Gradients</h3>
        <ul className="space-y-3 text-muted list-none pl-0">
          <li>
            <strong className="text-foreground">Linear Gradients:</strong> 
            Colors transition along a straight line. You can control the direction using an angle (e.g., 90deg) or keywords (e.g., to right, to bottom right).
          </li>
          <li>
            <strong className="text-foreground">Radial Gradients:</strong> 
            Colors emerge from a central point and radiate outwards in either a circle or an ellipse. You can move the origin point anywhere on the element.
          </li>
          <li>
            <strong className="text-foreground">Conic Gradients:</strong> 
            Colors transition rotated around a center point, much like a pie chart or a color wheel.
          </li>
        </ul>
      </div>
    </>
  );
}
